spring:
  application:
    name: Flight Service
    version: 0.0.1-SNAPSHOT


server:
  port: 8899
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50